const ActionType = {
  LOADING_OPEN: 'LOADING_OPEN',
  MESSAGE_SORRY: 'MESSAGE_SORRY',
  UNSET_MODAL: 'UNSET_MODAL',
  ADD_LIKE: 'ADD_LIKE',
  ADD_BOOKMARK: 'ADD_BOOKMARK',
  REMOVE_LIKE: 'REMOVE_LIKE',
  REMOVE_BOOKMARK: 'REMOVE_BOOKMARK',
  RESTORE: 'RESTORE',
  SET_THEME: 'SET_THEME',
}
export default ActionType
